#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

if xrandr -q | grep 'HDMI2 connected'; then
xrandr --output eDP1 --auto --primary
xrandr --output HDMI2 --auto --left-of eDP1
bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI2 -d VI VII VIII IX X
else
xrandr --output eDP1 --auto --primary
bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi
nitrogen --restore

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           0

bspc config normal_border_color "#4C566A"
bspc config focused_border_color "#8FBCBB"

bspc config top_padding 30
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
